# Standard Docker Compose for Uptime Kuma
# Source: https://github.com/louislam/uptime-kuma

services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      - "3001:3001"
